version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgesql/data
    ports:
      - '5432:5432'

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=nikburdo@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=mypassword
    ports:
      - '5050:80'

volumes:
  postgres:
